### ISSUE TITLE
[Feature request] Aurora theme

### ISSUE THREAD

**Issue by liho00** [tailwind-mobile/tailwind-mobile#4]
Aurora theme is needed for desktop & cross platform view, I would like to contribute a PR, izit i just need to replace the tailwind class as screenshot below in each of the components? Can we create the .scss file and apply the tailwind style and reuse the less variable just like how framework 7 https://framework7.io/docs/css-variables.html?

![image](https://user-images.githubusercontent.com/77238199/131714077-a1505390-78e3-45dc-97b8-41534dfeb513.png)

How do i or any interested community to be contributes in this ui library including documentations?

**Comment by nolimits4web** [comment]
> Can we create the .scss file and apply the tailwind style

Sorry, this is pretty much in conflict with main TW approach of using utility classes. Doing so will literally negate all the benefits of using Tailwind

**Comment by liho00** [comment]
> > Can we create the .scss file and apply the tailwind style
> 
> Sorry, this is pretty much in conflict with main TW approach of using utility classes. Doing so will literally negate all the benefits of using Tailwind

![image](https://user-images.githubusercontent.com/77238199/132013627-9f2cbb68-f52c-4323-ab04-858d6693d371.png)

if you put your tailwind class into the className direct, thats harded for developer to replace the same tailwind class, if the developer same using tailwind in his main project. eg. your component is using text-gray-500, but the developer want it to be text-gray-900, due to Tailwind class css order, it will not working as the text-gray-500 has the highest css order in the DOM.

check this out tailwind github issues: https://github.com/tailwindlabs/tailwindcss/issues/1010, https://github.com/tailwindlabs/tailwindcss/issues/1452
