### ISSUE TITLE
Suggest to write as Web Component

### ISSUE THREAD

**Issue by liho00** [tailwind-mobile/tailwind-mobile#5]
Have a look on this web components concept & functions, etc. https://developer.mozilla.org/en-US/docs/Web/Web_Components

I would suggest to use Vue js to develop web components. Hence you just write a single codebase, it can be used across any framework. https://v3.vuejs.org/guide/web-components.html#web-components-vs-vue-components

Based on my experience on React js, its hooks is very good to use, but its not friendly to write or use web component, we have to build a wrapper to use it with web component, but its still works well with web components, check this out https://reactjs.org/docs/web-components.html

**Comment by nolimits4web** [comment]
No way of doing it, can't see much advantages of such approach, and how to you suppose to deliver TW's classes styles to scoped web components?

**Comment by liho00** [comment]
> No way of doing it, can't see much advantages of such approach, and how to you suppose to deliver TW's classes styles to scoped web components?

Off cuz you can pass your TW class to the web component. For example ion-icon is a set of icon web component.
![image](https://user-images.githubusercontent.com/77238199/132013249-7562f39a-c2c4-4333-b851-5f4ee1735683.png)
![image](https://user-images.githubusercontent.com/77238199/132013426-c728ec97-7209-4992-9438-655bfc42b0c1.png)
reference link: https://ionic.io/ionicons/usage

**Comment by nolimits4web** [comment]
How can you use TW classes INSIDE of the web component?

**Comment by liho00** [comment]
> How can you use TW classes INSIDE of the web component?

dont u see the screenshot? I would like to suggest you create an empty project npm install ionic icon and tailwind, and then write in your tailwind class, its work for sure. Tailwind is just a Css utility class not a framework.
